### ISSUE TITLE
Rename repo from "Gamepad-mappings" to "gamepad-mappings"

### ISSUE THREAD

**Issue by toji** [immersive-web/xr-gamepad-mappings#17]
Yes, this is an absurd nit. But it's also currently the only repo in the immersive-web org that has a capital letter in it, so... 🤷‍♀️

**Comment by NellWaliczek** [comment]
Yeah... I'd noticed the same thing too ^_^  Whoops!

**Comment by NellWaliczek** [comment]
Renamed to xr-gamepad-mappings to match the package name
